app/teacher/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, FieldList, FormField, SelectMultipleField, widgets, DecimalField, FileField, IntegerField, RadioField, DateField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Regexp, NumberRange, Length
from app.models import User, Answer, Question, QuestionTopics, Topic
from wtforms.ext.sqlalchemy.fields import QuerySelectMultipleField, QuerySelectField
from functools import partial
from wtforms.widgets import TextArea
from wtforms import Form as NoCsrfForm

class AddExamForm(FlaskForm):
    exam_title = StringField('Exam Name', description="Ex: Exam 2", validators=[DataRequired(), Length(max=40)])
    exam_number = IntegerField('Exam Number', validators=[NumberRange(min=1, message='Please enter a non-negative number')])
    #exam_date = DateField('Exam Date', description='Format: day-month-year')
    cumulative = BooleanField('Cumulative Exam?', description="Note: this means that all prior content is fair game on this exam and students should study prior material about as much as the new content")

    topics = StringField('Exam Topics', description="Ex: Addition, Order of Operations, Division")

    submit = SubmitField('Submit')

class EditExamForm(FlaskForm):
    exam_title = StringField('Exam Name', description="Ex: Exam 2", validators=[DataRequired(), Length(max=40)])
    exam_number = IntegerField('Exam Number', validators=[NumberRange(min=1, message='Please enter a non-negative number')])
    #exam_date = DateField('Exam Date', description='Format: day-month-year')
    cumulative = BooleanField('Cumulative Exam?', description="Note: this means that all prior content is fair game on this exam and students should study prior material about as much as the new content")

    topics = StringField('Exam Topics', description="Ex: Addition, Order of Operations, Division")

    submit = SubmitField('Submit')

app/teacher/__init__.py
from flask import Blueprint

bp = Blueprint('teacher', __name__)

from app.teacher import routes

app/teacher/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, current_app
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from app import db
from app.models import User, Question, Answer, Topic, QuestionTopics, QuestionEval, School, Class, Exam, ExamTopics, Enrollment, ExamStructureSuggestion, QuestionAnswer, QuestionAnswerArgument, Section
from app.teacher.forms import AddExamForm, EditExamForm
from sqlalchemy.sql.expression import func
from sqlalchemy.sql import except_
import random
from collections import namedtuple
from sqlalchemy.orm import load_only
from app.teacher import bp

@bp.route('/teacher/')
@login_required
def index():
    if not current_user.teacher:
        return render_template('errors/404.html')

    sections = Section.query.filter_by(user_id=current_user.id)

    exams = []
    for section in sections:
        exams.append(Exam.query.filter_by(section_id=section.id))

    return render_template('teacher/index.html', title='Home', section_exams=zip(sections, exams))

@bp.route('/section/<section_id>/claim/')
@login_required
def claim_section(section_id):
    section = Section.query.filter_by(id=section_id).first_or_404()
    if section.user_id or not current_user.teacher:
        return render_template('errors/404.html')

    section.user_id = current_user.id
    db.session.add(section)
    db.session.commit()

    flash('Class Section' + section.body + ' claimed!')
    return redirect(url_for('teacher.manage_section', section_id=section_id))

@bp.route('/section/<section_id>/manage/')
@login_required
def manage_section(section_id):
    if not current_user.teacher:
        return render_template('errors/404.html')
    section = Section.query.filter_by(id=section_id).first_or_404()
    if not section.user_id:
        flash('Claim section before attempting to manage it!')
        redirect(url_for('main.section', section_id=section_id))
    if section.user_id != current_user.id:
        return render_template('errors/404.html')

    exams = Exam.query.filter_by(section_id=section_id).order_by(Exam.exam_number)

    topics = []
    for exam in exams:
        exam_topics = ExamTopics.query.filter_by(exam_id=exam.id)
        topics.append(exam_topics)

    invite_link = url_for('main.section_invite', section_id=section.id)

    return render_template('teacher/manage_section.html', section=section, exams=exams, exam_topics=zip(exams, topics), invite_link=invite_link)

@bp.route('/section/<section_id>/add_exam/', methods=['GET', 'POST'])
@login_required
def add_exam(section_id):
    section = Section.query.filter_by(id=section_id).first_or_404()
    if not current_user.teacher or not section.user_id or section.user_id != current_user.id:
        return render_template('errors/404.html')

    exams_count = Exam.query.count()

    form = AddExamForm()
    if form.validate_on_submit():
        exam = Exam(body=form.exam_title.data, exam_number=form.exam_number.data, cumulative=form.cumulative.data, section_id=section_id)
        db.session.add(exam)
        db.session.commit()
        flash('Your exam has been saved.')
        return redirect(url_for('teacher.manage_section', section_id=section_id))
    elif request.method == 'GET':
        form.exam_number.data = exams_count + 1
        form.exam_title.data = 'Exam ' + str(exams_count + 1)

    return render_template('teacher/add_exam.html', section=section, form=form)

@bp.route('/exam/<exam_id>/edit_exam/', methods=['GET', 'POST'])
@login_required
def edit_exam(exam_id):
    exam = Exam.query.filter_by(id=exam_id).first_or_404()
    section = Section.query.filter_by(id=exam.section.id).first_or_404()
    if not current_user.teacher or not section.user_id or section.user_id != current_user.id:
        return render_template('errors/404.html')

    form = EditExamForm()
    if form.validate_on_submit():
        exam.body = form.exam_title.data
        exam.exam_number = form.exam_number.data
        exam.cumulative = form.cumulative.data
        db.session.add(exam)
        db.session.commit()
        flash('Your exam has been saved.')
        return redirect(url_for('teacher.manage_section', section_id=section.id))
    elif request.method == 'GET':
        form.exam_number.data = exam.exam_number
        form.exam_title.data = exam.body
        form.cumulative.data = exam.cumulative

    return render_template('teacher/edit_exam.html', section=section, form=form, exam=exam)

app/templates/teacher/_manage_exam.html
<div class="card m-3" style="width: 18rem;">
    <div class="card-body d-flex flex-column">
        <a href="{{ url_for('main.exam', exam_id=exam.id, section_id=exam.section.id) }}" class="text-dark">
            <h3 class="card-title">{{ exam.body }}</h3>
        </a>
        <h6 class="card-subtitle mb-2 text-muted">
            {% for exam_topic in exam_topics %}
                <span class="badge badge-secondary">{{ exam_topic.topic.body }}</span>
            {% endfor %}
        </h6>
        {% if exam.description %}
            <p class="card-text">{{ exam.description }}</p>
        {% endif %}

        <a href="{{ url_for('teacher.edit_exam', exam_id=exam.id) }}" class="btn btn-outline-secondary mb-2">Edit Exam Properties</a>
        <a href="{{ url_for('main.exam', exam_id=exam.id, section_id=exam.section.id) }}" class="btn btn-outline-secondary mb-2">Add Associated Assignment</a>
        <a href="{{ url_for('main.remove_exam', exam_id=exam.id) }}" class="btn btn-outline-danger mb-2">Delete Exam</a>
    </div>
</div>

app/templates/teacher/add_exam.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form, render_field %}

{% block app_content %}
<div class="card">
    <div class="card-body flex-column">
        <h3 class="card-title">Add an exam for {{ section.class_.body }}, Section {{ section.body }}</h3>
        <br>
        <div class="row">
            <div class="col">
                {{ render_form(form) }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/teacher/edit_exam.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form, render_field %}

{% block app_content %}
<div class="card">
    <div class="card-body flex-column">
        <h3 class="card-title">Edit {{ exam.body }} for {{ section.class_.body }}, Section {{ section.body }}</h3>
        <br>
        <div class="row">
            <div class="col">
                {{ render_form(form) }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/teacher/index.html
{% extends "base.html" %}

{% block app_content %}

{% if current_user.is_authenticated %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">{{ current_user.school.body }}</li>
    </ol>
</nav>
<div class="jumbotron">
    <h1 class="display-4">Hey Professor {{ current_user.name.capitalize() }}!</h1>
    <p class="lead">Set up new classes or manage your current classes below!</p>
    <a class="btn btn-primary" href="{{ url_for('main.index') }}">Student View</a>
</div>
{% endif %}

{% for section, exams in section_exams %}
    {% include 'user/_class.html' %}
{% endfor %}

{% endblock app_content %}

app/templates/teacher/manage_section.html
{% extends "base.html" %}

{% block app_content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">{{ section.class_.school.body }}</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('main.class_', class_id=section.class_.id) }}">{{ section.class_.body }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ section.body }}</li>
    </ol>
</nav>
<div class="jumbotron">
    <h1 class="display-4">{{ section.class_.body }}</h1>
    <p class="lead">{{ section.class_.description }}</p>
    {% if current_user.id == section.user_id %}
    <a class="btn btn-primary" href="#"> You own this section </a>
    <br>
    <h3>Class Section Invite Link (students): <span class="badge badge-secondary">127.0.0.1:5000{{ invite_link }}</span></h3>
    {% endif %}
</div>

<div class="row">
    {% for exam, exam_topics in exam_topics %}
        {% include 'teacher/_manage_exam.html' %}
    {% endfor %}
</div>

<div class="card mt-3">
    <div class="card-header">
        Add Exams
    </div>
    <div class="card-body">
        <h5 class="card-title">Want to add or remove exams?</h5>
        <p class="card-text">Students will create study sets specific to each exam, so make sure the exam structure matches your class' exam structure!</p>
        <a href="{{ url_for('teacher.add_exam', section_id=section.id) }}" class="btn btn-primary">Add exam</a>
    </div>
</div>
{% endblock app_content %}