app/exams/__init__.py
from flask import Blueprint

bp = Blueprint('exams', __name__)

from app.exams import routes

app/exams/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, current_app
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from app import db
from app.models import User, Question, Answer, Topic, QuestionTopics, QuestionEval, School, Class, Exam, ExamTopics, Enrollment, ExamStructureSuggestion, QuestionAnswer, QuestionAnswerArgument
from app.exams.forms import ExamShortAnswerQuestion, OpenEndedAnswerEval
from sqlalchemy.sql.expression import func
from sqlalchemy.sql import except_
import random
from collections import namedtuple
from sqlalchemy.orm import load_only
from app.exams import bp
from app.models import OpenEndedQuestionAttempt, QuestionAnswer

@bp.route('/class/<class_id>/exam/<exam_id>/exam/', methods=['GET', 'POST'])
@login_required
def exam(class_id, exam_id):
    exam = Exam.query.filter_by(id = exam_id, class_id = class_id).first_or_404()

    question = Question.query.order_by(func.random()).first_or_404()

    form = ExamShortAnswerQuestion();

    if form.validate_on_submit():
        qAnswer = QuestionAnswer.query.filter_by(question_id=question.id).order_by(QuestionAnswer.correctness_score).first_or_404()

        questionAttempt = OpenEndedQuestionAttempt(user_id=current_user.id, question_id=question.id, answer_id=qAnswer.answer.id, body=form.answer.data)
        db.session.add(questionAttempt)
        db.session.commit()
        db.session.refresh(questionAttempt)

        return redirect(url_for('exams.attempt', exam_id=exam_id, class_id=class_id, attempt_id=questionAttempt.id))

    return render_template('exams/short_answer_question.html', title="Exam", exam=exam, question=question, form=form)

@bp.route('/class/<class_id>/exam/<exam_id>/exam/<attempt_id>/', methods=['GET', 'POST'])
@login_required
def attempt(class_id, exam_id, attempt_id):
    exam = Exam.query.filter_by(id = exam_id, class_id = class_id).first_or_404()

    attempt = OpenEndedQuestionAttempt.query.filter_by(id=attempt_id).first_or_404()

    form = OpenEndedAnswerEval();

    if form.validate_on_submit():
        if form.next.data:
            return redirect(url_for('exams.exam', exam_id=exam_id, class_id=class_id))
        elif form.submit.data:
            return redirect(url_for('main.exam', exam_id=exam_id, class_id=class_id))

    return render_template('exams/short_answer_question_result.html', attempt=attempt, exam=exam, form=form)

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, current_app
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from app import db
from app.models import User, Question, Answer, Topic, QuestionTopics, QuestionEval, School, Class, Exam, ExamTopics, Enrollment, ExamStructureSuggestion, QuestionAnswer, QuestionAnswerArgument, StudySetTerm, Section
from app.main.forms import NewQuestionForm, NewTopicForm, DeleteQuestionForm, ReviewQuestionForm, QuizQuestion, NewSubjectForm, EditExamStructureForm, EvaluateQuestionSubForm, ContributeForm, ProposeClassForm, ProposeTopicForm, NewQuestionForm, ProposeSectionForm
from sqlalchemy.sql.expression import func
from sqlalchemy.sql import except_
import random
from collections import namedtuple
from sqlalchemy.orm import load_only
from app.main import bp

@bp.route('/')
@bp.route('/index')
@bp.route('/home')
def index():
    enrollable_sections = []
    enrollment_sections = []
    enrolled = []
    enrolled_classes = []
    unenrolled_sections = []
    unenrolled = []
    unenrolled_classes = []

    unenrolled_count = 0
    enrolled_count = 0

    if current_user.is_authenticated:
        classes = Class.query.filter_by(school_id=current_user.school_id, approved=True).limit(25);

        for class_element in classes:
            if db.session.query(Enrollment.id).filter_by(class_id=class_element.id, user_id=current_user.id).first() is not None:
                enrollable_sections_temp = Section.query.filter_by(class_id = class_element.id).limit(9)
                enrollable_sections.append(enrollable_sections_temp)
                enrollment_status = []
                for section in enrollable_sections_temp:
                    if Enrollment.query.filter_by(section_id=section.id, user_id=current_user.id).first() is not None:
                        enrollment_status.append(True)
                    else:
                        enrollment_status.append(False)
                enrollment_sections.append(enrollment_status)
                enrolled.append(True)
                enrolled_classes.append(class_element)
                enrolled_count += 1
            else:
                unenrolled_sections.append(Section.query.filter_by(class_id = class_element.id).limit(9))
                unenrolled.append(False)
                unenrolled_classes.append(class_element)
                unenrolled_count += 1

        classes = Class.query.filter_by(school_id=current_user.school_id, approved=False).limit(25);

        for class_element in classes:
            if db.session.query(Enrollment.id).filter_by(class_id=class_element.id, user_id=current_user.id).first() is not None:
                enrollable_sections_temp = Section.query.filter_by(class_id = class_element.id).limit(9)
                enrollable_sections.append(enrollable_sections_temp)
                enrollment_status = []
                for section in enrollable_sections_temp:
                    if Enrollment.query.filter_by(section_id=section.id, user_id=current_user.id).first() is not None:
                        enrollment_status.append(True)
                    else:
                        enrollment_status.append(False)
                enrollment_sections.append(enrollment_status)
                enrolled.append(True)
                enrolled_classes.append(class_element)
                enrolled_count += 1

    else:
        classes = Class.query.filter_by(approved=True).limit(25);

        for class_element in classes:
            unenrolled_sections.append(Section.query.filter_by(class_id = class_element.id).limit(9))
            unenrolled.append(False)
            unenrolled_classes.append(class_element)
            unenrolled_count += 1

    section_pairs = zip(enrollment_sections, enrollable_sections)

    return render_template('main/index.html', title='Home', enrolled_classes = enrolled_count, unenrolled_classes = unenrolled_count, enrolled_class_sections=zip(enrolled_classes, enrollable_sections, enrolled, enrollment_sections), unenrolled_class_sections=zip(unenrolled_classes, unenrolled_sections, unenrolled), zip=zip)

@bp.route('/suggested_classes/')
@login_required
def suggested_classes():
    enrolled_sections = []
    enrolled = []
    enrolled_classes = []
    unenrolled_sections = []
    unenrolled = []
    unenrolled_classes = []

    unenrolled_count = 0
    enrolled_count = 0

    if current_user.is_authenticated:
        classes = Class.query.filter_by(school_id=current_user.school_id, approved=False).limit(25);

        for class_element in classes:
            if db.session.query(Enrollment.id).filter_by(class_id=class_element.id, user_id=current_user.id).first() is not None:
                enrolled_sections.append(Section.query.filter_by(class_id = class_element.id).limit(9))
                enrolled.append(True)
                enrolled_classes.append(class_element)
                enrolled_count += 1
            else:
                unenrolled_sections.append(Section.query.filter_by(class_id = class_element.id).limit(9))
                unenrolled.append(False)
                unenrolled_classes.append(class_element)
                unenrolled_count += 1

        classes = Class.query.filter_by(school_id=current_user.school_id, approved=False).limit(25);

        for class_element in classes:
            if db.session.query(Enrollment.id).filter_by(class_id=class_element.id, user_id=current_user.id).first() is not None:
                enrolled_sections.append(Section.query.filter_by(class_id = class_element.id).limit(9))
                enrolled.append(True)
                enrolled_classes.append(class_element)
                enrolled_count += 1

    else:
        classes = Class.query.filter_by(approved=False).limit(25);

        for class_element in classes:
            unenrolled_sections.append(Section.query.filter_by(class_id = class_element.id).limit(9))
            unenrolled.append(False)
            unenrolled_classes.append(class_element)
            unenrolled_count += 1

    return render_template('main/suggested_classes.html', title='Proposed Classes', enrolled_classes = enrolled_count, unenrolled_classes = unenrolled_count, enrolled_class_sections=zip(enrolled_classes, enrolled_sections, enrolled), unenrolled_class_sections=zip(unenrolled_classes, unenrolled_sections, unenrolled), zip=zip)

@bp.route('/suggested_classes/propose_class', methods=['GET', 'POST'])
@login_required
def propose_class():
    form = ProposeClassForm()

    if form.validate_on_submit():
        new_class = Class(approved=False, body=form.body.data, readable=form.title.data, description=form.description.data, user_id=current_user.id, school_id=current_user.school_id)
        db.session.add(new_class)
        db.session.commit()

        return redirect(url_for('main.suggested_classes'))

    return render_template('main/suggest_class.html', form=form)

@bp.route('/class/<class_id>/')
@login_required
def class_(class_id):
    class_element = Class.query.filter_by(id=class_id).first_or_404();

    sections = Section.query.filter_by(class_id=class_id)

    enrollment = []
    for section in sections:
        if Enrollment.query.filter_by(section_id=section.id, user_id=current_user.id).first() is not None:
            enrollment.append(True)
        else:
            enrollment.append(False)

    return render_template('main/class.html', title=class_element.body, class_element=class_element, sections_enrollment=zip(sections, enrollment))

@bp.route('/class/<class_id>/section/<section_id>/')
@login_required
def section(class_id, section_id):
    section = Section.query.filter_by(id=section_id).first_or_404();

    class_element = Class.query.filter_by(id=class_id).first_or_404();

    exams = Exam.query.filter_by(section_id = section_id);

    enrollment_element = Enrollment.query.filter_by(user_id=current_user.id, class_id=class_id, section_id=section_id).first()
    if enrollment_element is None:
        enrolled = False
    else:
        enrolled = True

    exam_topics = []
    for exam in exams:
        exam_topics.append(ExamTopics.query.filter_by(exam_id=exam.id).limit(9))

    return render_template('main/section.html', title=class_element.body, enrolled=enrolled, class_element=class_element, exam_topics_all=zip(exams, exam_topics), section=section)

@bp.route('/class/<class_id>/suggest_class_section/', methods=['GET', 'POST'])
@login_required
def suggested_class_section(class_id):

    class_element = Class.query.filter_by(id=class_id).first_or_404();

    form = ProposeSectionForm();
    if form.validate_on_submit():
        section = Section(body=form.body.data, description=form.description.data, approved=False, class_id=class_id)
        db.session.add(section)
        db.session.commit()

        flash('Your suggestion has been recieved!')
        return redirect(url_for('main.class_', class_id=class_id))

    return render_template('main/suggest_class_section.html', title='Propose Class Section', class_element=class_element, form=form)


@bp.route('/class/<class_id>/section/<section_id>/suggest_exam_structure/', methods=['GET', 'POST'])
@login_required
def suggested_exam_structure(class_id, section_id):

    section = Section.query.filter_by(id=section_id).first_or_404();

    form = EditExamStructureForm();
    if form.validate_on_submit():
        structure = ExamStructureSuggestion(body=form.comment.data, exam_count=form.exams.data, final_exam=form.final_exam.data, final_exam_cumulative=form.final_exam_cumulative.data, user_id=current_user.id, section_id=section_id, approved=False)
        db.session.add(structure)
        db.session.commit()

        if ExamStructureSuggestion.query.filter_by(section_id=section_id).count() == 1 and Exam.query.filter_by(section_id=section_id).count() == 0:
            for i in range(1, structure.exam_count + 1):

app/topics/__init__.py
from flask import Blueprint

bp = Blueprint('topics', __name__)

from app.topics import routes

app/topics/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, current_app
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from app import db
from app.models import ExamTopics, Question, QuestionTopics, QuestionEval
from app.topics import bp
from flask import abort
from sqlalchemy.orm import load_only

@bp.route('/class/<class_id>/exam/<exam_id>/topic/<topic_id>/', methods=['GET', 'POST'])
@login_required
def topic(class_id, exam_id, topic_id):
    exam_topic = ExamTopics.query.filter_by(exam_id=exam_id, topic_id=topic_id).first_or_404()

    topic_questions = QuestionTopics.query.filter_by(topic_id=exam_topic.topic.id).subquery()

    # Select questions that have been evaluated by this user
    current_user_questions = Question.query.filter_by(user_id=current_user.id).options(load_only(Question.id)).subquery()
    current_user_evaluated = db.session.query(QuestionEval.question_id).filter_by(user_id=current_user.id).subquery()

    # Select questions that user has submitted to this topic
    user_topic_questions = QuestionTopics.query.filter_by(topic_id=exam_topic.topic_id).filter(QuestionTopics.question_id.in_(current_user_questions)).subquery()

    current_user_topic_evaluations = db.session.query(QuestionEval.question_id).filter_by(user_id=current_user.id).outerjoin(topic_questions, topic_questions.c.question_id == QuestionEval.question_id).filter_by(topic_id=exam_topic.topic_id).subquery()

    unlock_percent = db.session.query(current_user_topic_evaluations).count() * 5 + db.session.query(user_topic_questions).count() * 25
    question_count = db.session.query(topic_questions).count()

    level_subtractor = 0
    i = unlock_percent - 100
    j = 0
    while i > 0:
        level_subtractor += (100 + 5 * j)
        i = i - (100 + 5 * j)
        j += 1

    level = j + 1

    return render_template('topics/topic.html', exam_topic=exam_topic, level=level, percent=unlock_percent, level_subtractor=level_subtractor, question_count=question_count)

app/user/__init__.py
from flask import Blueprint

bp = Blueprint('user', __name__)

from app.user import routes

app/user/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, current_app
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from app import db
from app.models import User, Question, Topic, QuestionTopics, Class, Exam, ExamTopics, Enrollment, ExamStructureSuggestion, School
from app.user.forms import EditProfileForm
from app.user import bp
from flask import abort

@bp.route('/admin/')
@login_required
def admin():
    if not current_user.admin:
        abort(404)

    pending_exam_structures = ExamStructureSuggestion.query.filter_by(approved=False).limit(20)
    classes = Class.query.filter_by(approved=False).limit(20)
    questions = Question.query.order_by(Question.timestamp).limit(20)

    topics = []
    for question in questions:
        topics.append(QuestionTopics.query.filter_by(question_id = question.id))

    return render_template('user/admin.html', title='Admin Dashboard', question_topics=zip(questions,topics), exam_structure_suggestions=pending_exam_structures, classes=classes)

@bp.route('/profile/')
@login_required
def user_profile():
    user = current_user
    questions = Question.query.filter_by(user_id=user.id).order_by(Question.id.desc()).limit(20)
    enrollments = Enrollment.query.filter_by(user_id=user.id).limit(20)

    sections = []
    exams = []
    for enrollment in enrollments:
        sections.append(enrollment.section)
        exams.append(Exam.query.filter_by(section_id=enrollment.section_id))

    return render_template('user/user.html', user=user, questions=questions, section_exams=zip(sections, exams))

@bp.route('/edit_profile/', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    form.school.query = School.query.all()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.name = form.name.data
        current_user.school_id = form.school.data.id
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('user.user_profile', username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.name.data = current_user.name
    return render_template('user/edit_profile.html', title='Edit Profile',
                           form=form)

app/templates/main/_question.html
<div class="card m-3" style="width: 18rem;">
  <div class="card-body">
    <h3 class="card-title">{{ question.body }}</h3>
  </div>
</div>

app/templates/main/_set_question.html
<div class='input-group mb-2 mt-2'>
    {% if term %}
    <textarea id='question{{ term.id }}' qterm_id='{{ term.id }}' type='text' aria-label='Question' placeholder='Question' class='form-control mr-3 textarea-autosize'>{{ term.question_answer.question.body }}</textarea>
    <textarea id='answer{{ term.id }}' aterm_id='{{ term.id }}' type='text' aria-label='Answer' placeholder='Answer' class='form-control mr-3 textarea-autosize'>{{ term.question_answer.answer.body }}</textarea>
    <span id='altans{{ term.id }}' altans_id='{{ term.id }}'>
        <a href="javascript:altans(
                    {{ term.id }});" type='button' class='btn btn-primary'>
            <i class="bi bi-chevron-down"></i>
        </a>
    </span>
    <span id='save{{ term.id }}' save_id='{{ term.id }}'>
        <a href="javascript:save(
                    '{{ term.id }}');" type='button' class='btn btn-success'>
            <i class="bi bi-cloud"></i>
        </a>
    </span>
    <span id='delete{{ term.id }}' dterm_id='{{ term.id }}'>
        <a href="javascript:deletesaved(
                    '{{ term.id }}');" type='button' class='btn btn-danger'>
            {% include 'icons/_trash_icon.html' %}
        </a>
    </span>
</div>
<div id="altansbtns{{ term.id }}" altansbtns_id='{{ term.id }}' style="display: none"></div>
    {% else %}
    <textarea id='nquestion0' qterm_id='-1' type='text' aria-label='Question' placeholder='Question' class='form-control mr-3 textarea-autosize'></textarea>
    <textarea id='nanswer0' aterm_id='-1' type='text' aria-label='Answer' placeholder='Answer' class='form-control mr-3 textarea-autosize'></textarea>
    <span id='altans0' altans_id='-1'>
        <a href="javascript:altans(
                    '-1');" type='button' class='btn btn-secondary'>
            <i class="bi bi-chevron-down"></i>
        </a>
    </span>
    <span id='nsave0' save_id='-1'>
        <a href="javascript:save('-1');" type='button' class='btn btn-success'>
            <i class="bi bi-cloud"></i>
        </a>
    </span>
    <span id='ndelete0' dterm_id='-1'>
        <a href="javascript:deletelocal('#ndelete0');" type='button' class='btn btn-danger'>
            {% include 'icons/_trash_icon.html' %}
        </a>
    </span>
</div>
<div id="altansbtns-1" altansbtns_id='-1' style="display: none"></div>
    {% endif %}

app/templates/main/contribute_eval.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form, render_field %}

{% block app_content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">{{ exam.exam_class.school.body }}</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('main.class_', class_id=exam.exam_class.id) }}">{{ exam.exam_class.body }}</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('main.exam', class_id=exam.exam_class.id, exam_id=exam.id) }}">{{ exam.body }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Evaluate Questions</li>
    </ol>
</nav>
    {% if eval_questions > 0 %}
    {% if topic %}
    <div class="jumbotron mt-3">
        <h2 class="display-5">Evaluating questions from topic: {{ topic.body }}</h2>
        <h2 class="card-subtitle mb-2 text-muted">
            <span class="badge badge-secondary">{{ exam.exam_class.body }}</span>
            <span class="badge badge-secondary">{{ exam.body }}</span>
        </h2>
    </div>
    {% else %}
    <div class="jumbotron mt-3">
        <h2 class="display-5">Evaluating questions from {{ exam.body }}</h2>
        <h2 class="card-subtitle mb-2 text-muted">
            <span class="badge badge-secondary">{{ exam.exam_class.body }}</span>
        </h2>
    </div>
    {% endif %}


    <div class="my-3 p-3 bg-light rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2">Enrolled Classes:</h6>
        <div class="row pr-3 pl-3">
            <form method="post" action="">
                {{ form.hidden_tag() }}
                {{ form.id }}
                {{ form.name }}
                <div class="row">
                {% for entry, question, question_topics in evaluate_forms %}
                    {% include 'main/_evaluate_question.html' %}
                {% endfor %}
                </div>
                {{ render_field(form.submit, class="btn btn-primary btn-lg float-right mt-3 mr-3") }}
                <a href="{{ url_for('main.exam', class_id=exam.exam_class.id, exam_id=exam.id) }}" class="btn btn-secondary btn-lg float-right mt-3 mr-3">Back</a>
                {{ form.csrf_token }}
            </form>
        </div>
    </div>
    {% else %}
    <div class="jumbotron mt-3">
        <h2 class="display-4 mb-3">Woah. There aren't any more questions for you to evaluate</h2>
        <h3 class="card-subtitle mb-4 text-muted">
            Great job! Check back later to see if your classmates have added more questions.
        </h3>
        <a href="{{ url_for('main.exam', class_id=exam.exam_class.id, exam_id=exam.id) }}" class="btn btn-primary btn-lg m-2">Back to {{exam.exam_class.body}} {{exam.body}}</a>
    </div>
    {% endif %}

{% endblock %}

app/templates/main/section.html
{% extends "base.html" %}

{% block app_content %}

{% if current_user.is_authenticated %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">{{ class_element.school.body }}</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('main.class_', class_id=class_element.id) }}">{{ class_element.body }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ section.body }}</li>
    </ol>
</nav>
{% if enrolled %}
<a href="{{ url_for('main.unenroll', class_id=class_element.id, section_id=section.id) }}" class="btn btn-secondary float-right m-3 font-weight-bold">Unenroll</a>
{% else %}
<a href="{{ url_for('main.enroll', class_id=class_element.id, section_id=section.id) }}" class="btn btn-primary float-right m-3 font-weight-bold">Enroll</a>
{% endif %}
<div class="jumbotron">
    <h1 class="display-4">{{ class_element.body }}</h1>
    <p class="lead">{{ class_element.description }}</p>
    {% if current_user.teacher and not section.user_id %}
    <a class="btn btn-primary" href="{{ url_for('teacher.claim_section', section_id=section.id) }}"> Claim Section </a>
    {% endif %}
    {% if section.user_id == current_user.id %}
    <a class="btn btn-primary" href="{{ url_for('teacher.manage_section', section_id=section.id) }}"> Manage Section </a>
    {% endif %}
</div>
{% else %}
<div class="jumbotron mt-3">
    <h1 class="display-4">Hey there!</h1>
    <p class="lead">Let's get you quizzing! Click the button below to start!</p>
    <a class="btn btn-primary" href="{{ url_for('auth.login') }}"> Log in/Register </a>
</div>
{% endif %}
<div class="row">
    {% for exam, exam_topics in exam_topics_all %}
        {% include 'main/_exam.html' %}
    {% endfor %}
</div>

<div class="card mt-3">
    <div class="card-header">
        Suggest New Exams
    </div>
    <div class="card-body">
        <h5 class="card-title">Are we missing an exam?</h5>
        <p class="card-text">Let us know!</p>
        <a href="{{ url_for('main.suggested_exam_structure', class_id=class_element.id, section_id=section.id) }}" class="btn btn-primary">Submit Exam Revision</a>
    </div>
</div>
{% endblock app_content %}

app/templates/main/suggested_classes.html
{% extends "base.html" %}

{% block app_content %}

{% if current_user.is_authenticated %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">{{ current_user.school.body }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Proposed Classes</li>
    </ol>
</nav>

<div class="jumbotron">
    <h1 class="display-4">Suggested Classes for {{ current_user.school.body }}</h1>
    <p class="lead">Click "enroll" on one of the subjects below to get notified when it gets added!</p>
</div>
{% else %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Proposed Classes</li>
    </ol>
</nav>

<div class="jumbotron mt-3">
    <h1 class="display-4">Hey there!</h1>
    <p class="lead">Let's get you quizzing! Click the button below to start!</p>
    <a class="btn btn-primary" href="{{ url_for('auth.login') }}"> Log in/Register </a>
</div>
{% endif %}

{% if enrolled_classes > 0 %}
<div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Enrolled Classes:</h6>
    <div class="row">
    {% for class, sections, enrolled in enrolled_class_exams %}
        {% if enrolled %}
            {% include 'main/_class.html' %}
        {% endif %}
    {% endfor %}
    </div>
</div>
{% endif %}

{% if unenrolled_classes > 0 %}
<div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Other Classes:</h6>
    <div class="row">
    {% for class, sections, enrolled in unenrolled_class_sections %}
        {% if not enrolled %}
            {% include 'main/_class.html' %}
        {% endif %}
    {% endfor %}
    </div>
</div>
{% endif %}

<div class="card mt-3">
    <div class="card-header">
        Suggest New Class
    </div>
    <div class="card-body">
        <h5 class="card-title">Can't find the class you're looking for?</h5>
        <p class="card-text">Suggest a new class</p>
        <a href="{{ url_for('main.propose_class') }}" class="btn btn-primary">Propose class</a>
    </div>
</div>

{% endblock app_content %}

app/templates/main/user.html
{% extends "base.html" %}

{% block app_content %}
    <div class="jumbotron mt-3">
        <h1 class="display-4">Hey {{ current_user.name.capitalize() }}!</h1>
        <p class="lead">You look great today</p>
        {% if user == current_user %}
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{{ url_for('main.edit_profile') }}" role="button">Edit your profile</a>
        </p>
        {% endif %}
    </div>

    {% if enrolled %}
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h6 class="border-bottom border-gray pb-2 mb-0">Enrolled Classes:</h6>
            <div class="row">
            {% for class, exams in class_exams %}
                {% include 'main/_class.html' %}
            {% endfor %}
            </div>
        </div>
    {% endif %}

    {% if unenrolled %}
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h6 class="border-bottom border-gray pb-2 mb-0">Waitlisted Classes (pending approval):</h6>
            <div class="row">
            {% for class, exams in unenrolled_class_exams %}
                {% include 'main/_class.html' %}
            {% endfor %}
            </div>
        </div>
    {% endif %}

    {% if questions %}
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h6 class="border-bottom border-gray pb-2 mb-0">Questions you contributed:</h6>
            <div class="row">
            {% for question in questions %}
                {% include 'main/_question.html' %}
            {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}