app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import ValidationError, DataRequired, Regexp
from app.models import User

class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    name = StringField('First Name', validators=[DataRequired(), Regexp('^([A-Za-z][A-Za-z\'\-]*)$', message="Names must contain only letters and apostrophes")])
    school = QuerySelectField()
    submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')

app/user/__init__.py
from flask import Blueprint

bp = Blueprint('user', __name__)

from app.user import routes

app/user/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, current_app
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from app import db
from app.models import User, Question, Topic, QuestionTopics, Class, Exam, ExamTopics, Enrollment, ExamStructureSuggestion, School
from app.user.forms import EditProfileForm
from app.user import bp
from flask import abort

@bp.route('/admin/')
@login_required
def admin():
    if not current_user.admin:
        abort(404)

    pending_exam_structures = ExamStructureSuggestion.query.filter_by(approved=False).limit(20)
    classes = Class.query.filter_by(approved=False).limit(20)
    questions = Question.query.order_by(Question.timestamp).limit(20)

    topics = []
    for question in questions:
        topics.append(QuestionTopics.query.filter_by(question_id = question.id))

    return render_template('user/admin.html', title='Admin Dashboard', question_topics=zip(questions,topics), exam_structure_suggestions=pending_exam_structures, classes=classes)

@bp.route('/profile/')
@login_required
def user_profile():
    user = current_user
    questions = Question.query.filter_by(user_id=user.id).order_by(Question.id.desc()).limit(20)
    enrollments = Enrollment.query.filter_by(user_id=user.id).limit(20)

    sections = []
    exams = []
    for enrollment in enrollments:
        sections.append(enrollment.section)
        exams.append(Exam.query.filter_by(section_id=enrollment.section_id))

    return render_template('user/user.html', user=user, questions=questions, section_exams=zip(sections, exams))

@bp.route('/edit_profile/', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    form.school.query = School.query.all()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.name = form.name.data
        current_user.school_id = form.school.data.id
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('user.user_profile', username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.name.data = current_user.name
    return render_template('user/edit_profile.html', title='Edit Profile',
                           form=form)

app/templates/user/_class.html
<div class="card m-3" style="width: 18rem;">
  <div class="card-body d-flex flex-column">
    <a href="{{ url_for('main.class_', class_id=section.class_.id) }}" class="text-dark">
    <h3 class="card-title">{{ section.class_.body }}</h3></a>
    <h6 class="card-subtitle mb-2 text-muted">
        {{ section.body }}
        {% for exam in exams %}
            <span class="badge badge-secondary">{{ exam.body }}</span>
        {% endfor %}
    </h6>

    <div class="mt-auto"></div>
    {% if section.description %}
        <p class="card-text">{{ section.description }}</p>
    {% endif %}

    <a href="{{ url_for('main.section', class_id=section.class_.id, section_id=section.id) }}" class="btn btn-outline-secondary mb-2">View</a>

  </div>
</div>

app/templates/user/admin.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form, render_field %}

{% block app_content %}
{% if current_user.is_authenticated and current_user.admin %}
<div class="jumbotron">
    <h1 class="display-4">Hey Admin {{ current_user.name.capitalize() }}!</h1>
    <p class="lead">Welcome to the Admin Dashboard!</p>
</div>
<br>
<div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Classes with Pending Exam Structures:</h6>
    <div class="row">
        {% for exam_structure_suggestion in exam_structure_suggestions %}
        <div class="card m-3" style="width: 18rem;">
            <div class="card-body">
                <h3 class="card-title">{{ exam_structure_suggestion.section.class_.body }}</h3>
                <h3 class="card-title">Section {{ exam_structure_suggestion.section.body }}</h3>
                <h5 class="card-subtitle">{{ exam_structure_suggestion.author.name }}</h5>
                <br>
                <h5 class="card-text">Exam Count: {{ exam_structure_suggestion.exam_count }}</h5>
                <h5 class="card-text">Quiz Count: {{ exam_structure_suggestion.quiz_count }}</h5>
                <h5 class="card-text">Final Exam: {{ exam_structure_suggestion.final_exam }}</h5>
                <h5 class="card-text">Final Cumulative: {{ exam_structure_suggestion.final_exam_cumulative }}</h5>
                <h5 class="card-text">Comment: {{ exam_structure_suggestion.comment }}</h5>
                <br>
                <a href="{{ '/exam_structure/%s/approve' % exam_structure_suggestion.id }}" class="btn btn-outline-primary stretched-link">Approve Structure</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Classes Pending Approval:</h6>
    <div class="row">
        {% for class in classes %}
        <div class="card m-3" style="width: 18rem;">
            <div class="card-body">
                <h3 class="card-title">{{ class.body }}</h3>
                <h5 class="card-subtitle">{{ class.author }}</h5>
                <br>
                <h5 class="card-text">Readable Name: {{ class.readable }}</h5>
                <h5 class="card-text">Description: {{ class.description }}</h5>
                <br>
                <a href="{{ '/class/%s/approve' % class.id }}" class="btn btn-outline-primary stretched-link">Approve Structure</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Recently Added Questions</h6>
    <div class="row">
        {% for question, topics in question_topics %}
        <div class="card m-3" style="width: 18rem;">
            <div class="card-body">
                <h3 class="card-title">{{ question.body }}</h3>
                {% for topic in topics %}
                <span class="badge badge-secondary">{{ topic.body }}</span>
                {% endfor %}
                <h5 class="card-subtitle">{{ question.author }}</h5>
                <br>
                <a href="{{ '/question/%s' % question.id }}" class="btn btn-outline-primary stretched-link">View Question</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="jumbotron mt-3">
    <h1 class="display-4">Hi there!</h1>
    <p class="lead">I'm not sure how you got here, but you don't have access to this page</p>
    <a class="btn btn-primary" href="{{ url_for('main.index') }}"> Back </a>
</div>
{% endif %}
{% endblock %}

app/templates/user/edit_profile.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form, render_field %}

{% block app_content %}
    <div class="jumbotron mt-3">
        <h1 class="display-4">Edit Profile</h1>
        <div class="row">
            <div class="col-md-4">
                {{ render_form(form) }}
            </div>
        </div>
    </div>
{% endblock %}

app/templates/user/user.html
{% extends "base.html" %}

{% block app_content %}
    <div class="alert alert-info" role="alert">If you are a teacher, please Contact Us to get your account upgraded</div>

    <div class="jumbotron mt-3">
        <h1 class="display-4">Hey {{ current_user.name.capitalize() }}!</h1>
        <p class="lead">You look great today</p>
        {% if user == current_user %}
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{{ url_for('user.edit_profile') }}" role="button">Edit your profile</a>
        </p>
        {% endif %}
    </div>

    {% if questions %}
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h6 class="border-bottom border-gray pb-2 mb-0">Recent questions you've added:</h6>
            <div class="row">
            {% for question in questions %}
                {% include 'main/_question.html' %}
            {% endfor %}
            </div>
        </div>
    {% endif %}

    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">Enrolled Classes:</h6>
        <div class="row">
        {% for section, exams in section_exams %}
            {% include 'user/_class.html' %}
        {% endfor %}
        </div>
    </div>

{% endblock %}